In [1]:
import os
import pandas as pd
import numpy as np
import time
import traceback

import warnings
warnings.filterwarnings("ignore")

In [2]:
%run "C:/Users/KISHORE/OneDrive/Desktop/Intelligent Weather Prediction Pipeline/src/data/data_ingestion.py"
%run "C:/Users/KISHORE/OneDrive/Desktop/Intelligent Weather Prediction Pipeline/src/data/data_validation.py"

current location:  C:\Users\KISHORE\OneDrive\Desktop\Intelligent Weather Prediction Pipeline\notebooks
loading time 0.32secs
Filename: C:\Users\KISHORE\OneDrive\Desktop\Intelligent Weather Prediction Pipeline\src\data\data_ingestion.py

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    31    125.3 MiB    125.3 MiB           1   @profile
    32                                         def load_data(filename):
    33    125.3 MiB      0.0 MiB           1       try:
    34    125.3 MiB      0.0 MiB           1           start = time.time()
    35    134.2 MiB      8.9 MiB           1           dataset = pd.read_csv(f"{filename}.csv")
    36    134.2 MiB      0.0 MiB           1           end = time.time()
    37    134.2 MiB      0.0 MiB           1           print(f"loading time {round(end-start,2)}secs")
    38                                             except Exception as e:
    39                                                 print("faild!")
    40                                                 traceback.print_exc()
    41    134.2 MiB      0.0 MiB           1       return dataset

In [3]:
os.chdir("C:/Users/KISHORE/OneDrive/Desktop/Intelligent Weather Prediction Pipeline")
from src.data import data_ingestion
from src.data import data_validation

In [4]:
np.set_printoptions(precision = 4 , suppress = True)
pd.set_option("display.float_format" , "{:.4f}".format)

In [5]:
weather_data = data_ingestion.load_data("open-meteo-26.61N81.26E120m")

loading time 0.22secs
Filename: C:\Users\KISHORE\OneDrive\Desktop\Intelligent Weather Prediction Pipeline\src\data\data_ingestion.py

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    31    135.8 MiB    135.8 MiB           1   @profile
    32                                         def load_data(filename):
    33    135.8 MiB      0.0 MiB           1       try:
    34    135.8 MiB      0.0 MiB           1           start = time.time()
    35    143.5 MiB      7.8 MiB           1           dataset = pd.read_csv(f"{filename}.csv")
    36    143.5 MiB      0.0 MiB           1           end = time.time()
    37    143.5 MiB      0.0 MiB           1           print(f"loading time {round(end-start,2)}secs")
    38                                             except Exception as e:
    39                                                 print("faild!")
    40                                                 traceback.print_exc()
    41    143.5 MiB      0.0 MiB           1       return dataset

In [6]:
weather_data.head(2)

,time,temperature_2m (°C),relative_humidity_2m (%),rain (mm),soil_temperature_0_to_7cm (°C),wind_speed_100m (km/h),surface_pressure (hPa),pressure_msl (hPa),is_day ()
0,2020-01-01T00:00,5.8000,93,0.0000,8.3000,15.1000,1004.5000,1019.4000,0
1,2020-01-01T01:00,5.7000,93,0.0000,8.0000,14.5000,1004.4000,1019.3000,0

In [7]:
weather_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52608 entries, 0 to 52607
Data columns (total 9 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   time                            52608 non-null  object
 1   temperature_2m (°C)             52608 non-null  float64
 2   relative_humidity_2m (%)        52608 non-null  int64
 3   rain (mm)                       52608 non-null  float64
 4   soil_temperature_0_to_7cm (°C)  52608 non-null  float64
 5   wind_speed_100m (km/h)          52608 non-null  float64
 6   surface_pressure (hPa)          52608 non-null  float64
 7   pressure_msl (hPa)              52608 non-null  float64
 8   is_day ()                       52608 non-null  int64
dtypes: float64(6), int64(2), object(1)
memory usage: 3.6+ MB

In [8]:
weather_data[weather_data.duplicated()]

Empty DataFrame
Columns: [time, temperature_2m (°C), relative_humidity_2m (%), rain (mm), soil_temperature_0_to_7cm (°C), wind_speed_100m (km/h), surface_pressure (hPa), pressure_msl (hPa), is_day ()]
Index: []

In [9]:
list(weather_data.columns)

['time',
 'temperature_2m (°C)',
 'relative_humidity_2m (%)',
 'rain (mm)',
 'soil_temperature_0_to_7cm (°C)',
 'wind_speed_100m (km/h)',
 'surface_pressure (hPa)',
 'pressure_msl (hPa)',
 'is_day ()']

In [10]:
weather_data.columns = weather_data.columns.str.strip()

In [11]:
weather_data.rename(columns = {
    "time" : "Date",
    "temperature_2m (°C)" : "Temperature",
    "relative_humidity_2m (%)" : "Relative_humidity",
    "rain (mm)" : "Rain",
    "soil_temperature_0_to_7cm (°C)" : "Soil_temperature",
    "wind_speed_100m (km/h)" : "Wind_speed",
    "surface_pressure (hPa)" : "Surface_pressure",
    "pressure_msl (hPa)" : "Pressure_msl",
    "is_day ()" : "is_day"
}, inplace = True)

In [12]:
weather_data.head()

,Date,Temperature,Relative_humidity,Rain,Soil_temperature,Wind_speed,Surface_pressure,Pressure_msl,is_day
0,2020-01-01T00:00,5.8000,93,0.0000,8.3000,15.1000,1004.5000,1019.4000,0
1,2020-01-01T01:00,5.7000,93,0.0000,8.0000,14.5000,1004.4000,1019.3000,0
2,2020-01-01T02:00,6.0000,93,0.0000,7.8000,12.7000,1004.6000,1019.4000,0
3,2020-01-01T03:00,5.8000,94,0.0000,7.6000,12.3000,1004.6000,1019.5000,0
4,2020-01-01T04:00,5.7000,95,0.0000,7.6000,13.1000,1004.7000,1019.6000,0

In [13]:
weather_data["Date"] = pd.to_datetime(weather_data["Date"])

In [14]:
data_validation.validate_dataset(weather_data)

'Dataset Validated Successfully.There is no any inconsisties in data!'

In [15]:
weather_data.head()

,Date,Temperature,Relative_humidity,Rain,Soil_temperature,Wind_speed,Surface_pressure,Pressure_msl,is_day
0,2020-01-01 00:00:00,5.8000,93,0.0000,8.3000,15.1000,1004.5000,1019.4000,0
1,2020-01-01 01:00:00,5.7000,93,0.0000,8.0000,14.5000,1004.4000,1019.3000,0
2,2020-01-01 02:00:00,6.0000,93,0.0000,7.8000,12.7000,1004.6000,1019.4000,0
3,2020-01-01 03:00:00,5.8000,94,0.0000,7.6000,12.3000,1004.6000,1019.5000,0
4,2020-01-01 04:00:00,5.7000,95,0.0000,7.6000,13.1000,1004.7000,1019.6000,0

In [16]:
weather_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52608 entries, 0 to 52607
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               52608 non-null  datetime64[ns]
 1   Temperature        52608 non-null  float64
 2   Relative_humidity  52608 non-null  int64
 3   Rain               52608 non-null  float64
 4   Soil_temperature   52608 non-null  float64
 5   Wind_speed         52608 non-null  float64
 6   Surface_pressure   52608 non-null  float64
 7   Pressure_msl       52608 non-null  float64
 8   is_day             52608 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(2)
memory usage: 3.6 MB

In [17]:
try:
    os.chdir("C:/Users/KISHORE/OneDrive/Desktop/Intelligent Weather Prediction Pipeline/data/interim")
    weather_data.to_csv("clean_weather_data.csv", index = False)
    print("file saved Successfully!")
except Exception as e:
    print("faild!")
    traceback.print_exc()

file saved Successfully!