# **Time Series Forcasting Project: Intelligent Weather Prediction Pipeline**

**Author:** Kishore Tirumani  
**Role:** Data Science Intern  
**Organization:** Khizex Software Solutions

**Start Date:** 07 July 2026

## Importing Necessary Libraies

In [1]:
import os
import pandas as pd
import time

import inspect
import psutil as ps
import sweetviz as sv

import warnings
warnings.filterwarnings("ignore")

In [2]:
#run data_ingestion file before using it
%run "C:/Users/KISHORE/OneDrive/Desktop/Intelligent Weather Prediction Pipeline/src/data/data_ingestion.py"

current location:  C:\Users\KISHORE\OneDrive\Desktop\Intelligent Weather Prediction Pipeline\notebooks
loading time 0.35secs
Filename: C:\Users\KISHORE\OneDrive\Desktop\Intelligent Weather Prediction Pipeline\src\data\data_ingestion.py

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    32    201.5 MiB    201.5 MiB           1   @profile
    33                                         def load_data(filename,filelocation):
    34                                             """
    35                                             Collects Weather data of Delhi for weather forcasting pipeline
    36
    37                                             Args:
    38                                                 filename(String): Name of the file
    39                                                 filelocation(String): file location in local machine
    40
    41                                             Returns:
    42                                                 Dataset(DataFrame): it contains past 5 Years delhi weather recors and variables
    43
    44                                             """
    45    201.5 MiB      0.0 MiB           1       os.chdir(filelocation)
    46    201.5 MiB      0.0 MiB           1       try:
    47    201.5 MiB      0.0 MiB           1           start = time.time()
    48    209.1 MiB      7.5 MiB           1           dataset = pd.read_csv(f"{filename}.csv")
    49    209.1 MiB      0.0 MiB           1           end = time.time()
    50    209.1 MiB      0.0 MiB           1           print(f"loading time {round(end-start,2)}secs")
    51                                             except Exception as e:
    52                                                 print("faild!")
    53                                                 traceback.print_exc()
    54    209.1 MiB      0.0 MiB           1       return dataset

In [3]:
os.chdir("C:/Users/KISHORE/OneDrive/Desktop/Intelligent Weather Prediction Pipeline")
#importing data_ingestion file
from src.data import data_ingestion

In [4]:
#defain basic setting for pandas DataFrame data format
pd.set_option("display.float_format" , "{:.4f}".format)

In [5]:
#lets see signature of load_data methon in data_ingestion module
inspect.signature(data_ingestion.load_data)

In [6]:
#description of the file
inspect.getdoc(data_ingestion.load_data).split("\n")

['Collects Weather data of Delhi for weather forcasting pipeline',
 '',
 'Args:',
 '    filename(String): Name of the file',
 '    filelocation(String): file location in local machine',
 '',
 'Returns:',
 '    Dataset(DataFrame): it contains past 5 Years delhi weather recors and variables']

## Data Loading & Inspection

In [7]:
weather_data = data_ingestion.load_data("open-meteo-26.61N81.26E120m","C:/Users/KISHORE/OneDrive/Desktop/Intelligent Weather Prediction Pipeline/data/raw")

loading time 0.35secs
Filename: C:\Users\KISHORE\OneDrive\Desktop\Intelligent Weather Prediction Pipeline\src\data\data_ingestion.py

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    32    204.0 MiB    204.0 MiB           1   @profile
    33                                         def load_data(filename,filelocation):
    34                                             """
    35                                             Collects Weather data of Delhi for weather forcasting pipeline
    36
    37                                             Args:
    38                                                 filename(String): Name of the file
    39                                                 filelocation(String): file location in local machine
    40
    41                                             Returns:
    42                                                 Dataset(DataFrame): it contains past 5 Years delhi weather recors and variables
    43
    44                                             """
    45    204.0 MiB      0.0 MiB           1       os.chdir(filelocation)
    46    204.0 MiB      0.0 MiB           1       try:
    47    204.0 MiB      0.0 MiB           1           start = time.time()
    48    209.7 MiB      5.8 MiB           1           dataset = pd.read_csv(f"{filename}.csv")
    49    209.7 MiB      0.0 MiB           1           end = time.time()
    50    209.7 MiB      0.0 MiB           1           print(f"loading time {round(end-start,2)}secs")
    51                                             except Exception as e:
    52                                                 print("faild!")
    53                                                 traceback.print_exc()
    54    209.7 MiB      0.0 MiB           1       return dataset

In [8]:
cpu_percent = ps.cpu_percent(interval=1)
print(f"CPU Usage: {cpu_percent}%")

CPU Usage: 96.6%

In [9]:
weather_data.head(3)

,time,temperature_2m (°C),relative_humidity_2m (%),rain (mm),soil_temperature_0_to_7cm (°C),wind_speed_100m (km/h),surface_pressure (hPa),pressure_msl (hPa),is_day ()
0,2020-01-01T00:00,5.8000,93,0.0000,8.3000,15.1000,1004.5000,1019.4000,0
1,2020-01-01T01:00,5.7000,93,0.0000,8.0000,14.5000,1004.4000,1019.3000,0
2,2020-01-01T02:00,6.0000,93,0.0000,7.8000,12.7000,1004.6000,1019.4000,0

In [10]:
weather_data.tail(3)

,time,temperature_2m (°C),relative_humidity_2m (%),rain (mm),soil_temperature_0_to_7cm (°C),wind_speed_100m (km/h),surface_pressure (hPa),pressure_msl (hPa),is_day ()
52605,2025-12-31T21:00,10.1000,96,0.0000,11.9000,8.9000,999.8000,1014.4000,0
52606,2025-12-31T22:00,9.3000,98,0.0000,11.4000,8.7000,999.9000,1014.5000,0
52607,2025-12-31T23:00,9.0000,100,0.0000,11.5000,12.1000,999.8000,1014.4000,0

In [11]:
weather_data.sample(n=500).head(3)

,time,temperature_2m (°C),relative_humidity_2m (%),rain (mm),soil_temperature_0_to_7cm (°C),wind_speed_100m (km/h),surface_pressure (hPa),pressure_msl (hPa),is_day ()
33778,2023-11-08T10:00,27.2000,53,0.0000,24.8000,10.8000,1001.7000,1015.4000,1
41623,2024-09-30T07:00,25.9000,91,0.0000,26.6000,9.9000,995.5000,1009.2000,1
46972,2025-05-11T04:00,26.9000,63,0.0000,28.5000,13.5000,990.7000,1004.3000,0

In [12]:
print("Shape of the dataset: ",weather_data.shape)
print("Size of the dataset: ",weather_data.size)

Shape of the dataset:  (52608, 9)
Size of the dataset:  473472

In [13]:
print("Memory Usage of the dataset is : ", weather_data.memory_usage(),end = "\n")

Memory Usage of the dataset is :  Index                                132
time                              420864
temperature_2m (°C)               420864
relative_humidity_2m (%)          420864
rain (mm)                         420864
soil_temperature_0_to_7cm (°C)    420864
wind_speed_100m (km/h)            420864
surface_pressure (hPa)            420864
pressure_msl (hPa)                420864
is_day ()                         420864
dtype: int64

In [14]:
weather_data.columns

Index(['time', 'temperature_2m (°C)', 'relative_humidity_2m (%)', 'rain (mm)',
       'soil_temperature_0_to_7cm (°C)', 'wind_speed_100m (km/h)',
       'surface_pressure (hPa)', 'pressure_msl (hPa)', 'is_day ()'],
      dtype='object')

In [15]:
d = {"Column": weather_data.columns, "Dtype" : weather_data.dtypes}
data_types_df = pd.DataFrame(d)
index = [""]*len(data_types_df)
data_types_df.index = index
data_types_df

                          Column    Dtype
                            time   object
             temperature_2m (°C)  float64
        relative_humidity_2m (%)    int64
                       rain (mm)  float64
  soil_temperature_0_to_7cm (°C)  float64
          wind_speed_100m (km/h)  float64
          surface_pressure (hPa)  float64
              pressure_msl (hPa)  float64
                       is_day ()    int64

In [16]:
os.chdir("C:/Users/KISHORE/OneDrive/Desktop/Intelligent Weather Prediction Pipeline/reports")
start = time.time()
report = sv.analyze(weather_data)
report.show_html("weather_data_basic_report.html")
end = time.time()
print(f"TIme taken: {round(end-start,2)}sec")
cpu_percent = ps.cpu_percent(interval=1)
print(f"CPU Usage: {cpu_percent}%")

                                             |                                             | [  0%]   00:00 ->…

Report weather_data_basic_report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.
TIme taken: 24.4sec
CPU Usage: 41.8%